import {StyleSheet} from 'react-native';
import colors from '../../utils/colors';
import {moderateScale} from '../../utils/commonnFunctions';

export default StyleSheet.create({
  container: {
    flex: 1,
    // paddingHorizontal: 12,
    paddingVertical: 12,
    position: 'relative',
  },
  remoteContainer: {
    flex: 1,
    marginTop: 8,
    zIndex: 1,
    margin: 10,
    borderRadius: 10,
    backgroundColor: colors.black,
    marginBottom: 120,
    overflow: 'hidden',
  },
  localContainer: {
    width: 100,
    height: 150,
    position: 'absolute',
    bottom: 130,
    right: 10,
    borderRadius: 8,
    zIndex: 12,
    overflow: 'hidden',
  },
  bottomBtnContainer: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'flex-end',
    zIndex: 123,
    backgroundColor: colors.bottomNavColor,
    paddingVertical: 12,
    bottom: 0,
    position: 'absolute',
    left: 0,
    right: 0,
  },
  btnContainer: {
    backgroundColor: colors.white,
    padding: 10,
    borderRadius: 8,
  },
  btnImage: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  callViewContainer: {
    flex: 1,
    position: 'absolute',
    left: 10,
    bottom: 90,
    right: 10,
    top: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    borderWidth: 6,
    borderColor: colors.primaryBlue,
  },
  callingContainer: {
    backgroundColor: colors.white,
    flex: 1,
  },
  callTitle: {
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerContainer: {
    paddingVertical: 10,
    color: colors.textColor,
  },
  timeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
  },
  ongoingCallImage: {
    width: 12,
    height: 12,
    resizeMode: 'contain',
    marginEnd: 5,
  },
  incommingCallContainer: {
    flex: 1,
    marginHorizontal: 10,
  },
  incommingCallUserImage: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  incommingCallInner: {
    flex: 1,
    marginTop: 8,
    zIndex: 1,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: colors.bottomNavColor,
    backgroundColor: 'rgba(0,0,0,0.7)',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  callPickIcon: {
    tintColor: colors.white,
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  callDismissIcon: {
    tintColor: colors.white,
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  responseIcons: {
    zIndex: 676,
    position: 'absolute',
    bottom: 80,
    left: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  callAnswerBtnContainer: {
    borderRadius: 30,
    height: 60,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  callingUserImage: {
    width: moderateScale(200),
    height: moderateScale(200),
    resizeMode: 'contain',
  },
});
