const fonts = {
  regular: 'Roboto-Regular',
  medium: 'Roboto-Medium',
  italic: 'Roboto-Italic',
  black: 'Roboto-Black',
  blackItalic: 'Roboto-BlackItalic',
  bold: 'Roboto-Bold',
  boldItalic: 'Roboto-BoldItalic',
  light: 'Roboto-Light',
  lightItalic: 'Roboto-LightItalic',
  mediumItalic: 'Roboto-MediumItalic',
  thin: 'Roboto-Thin',
  thinItalic: 'Roboto-ThinItalic',
  ssRegular: 'SourceSansPro-Regular',
  ssItalic: 'SourceSansPro-Italic',
  ssBlack: 'SourceSansPro-Black',
  ssBlackItalic: 'SourceSansPro-BlackItalic',
  ssBold: 'SourceSansPro-Bold',
  ssBoldItalic: 'SourceSansPro-BoldItalic',
  ssLight: 'SourceSansPro-Light',
  ssLightItalic: 'SourceSansPro-LightItalic',
  ssSemiBold: 'SourceSansPro-SemiBold',
  ssSemiBoldItalic: 'SourceSansPro-SemiBoldItalic',
  ssExtraLight: 'SourceSansPro-ExtraLight',
  ssExtraLigthItalic: 'SourceSansPro-ExtraLightItalic',
};
export default fonts;
