export default {
  search: require('../assets/images/search.png'),
  filter: require('../assets/images/filter.png'),
  edit: require('../assets/images/edit.png'),
  message: require('../assets/images/message.png'),
  phone: require('../assets/images/phone.png'),
  network: require('../assets/images/network.png'),
  user: require('../assets/images/user.png'),
  back: require('../assets/images/back.png'),
  send: require('../assets/images/send.png'),
  video: require('../assets/images/video.png'),
  phoneCall: require('../assets/images/phone-call.png'),
  audioOn: require('../assets/images/audio-on.png'),
  micOn: require('../assets/images/mic-on.png'),
  micOff: require('../assets/images/mic-off.png'),
  videoOn: require('../assets/images/video-on.png'),
  videoOff: require('../assets/images/video-off.png'),
  decline: require('../assets/images/decline.png'),
};
